---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demogcr
 labels:
   app: demogcr
spec:
 replicas: 2
 selector:
  matchLabels:
   app: demogcr
 template:
  metadata:
   labels:
    app: demogcr
  spec:
   containers:
   - name: demogcr
     image: prativsp/demogcr:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: demogcr
spec:
 type: LoadBalancer
 selector:
  app: demogcr
 ports:
  - protocol: TCP
    port: 5602
    targetPort: 8080
